# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='rp maker v2', kernelModule='rp_maker', kernelFunction='RF_on_Circle_Coupling', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)

RsgPickButton(
    p="DialogBox",
    text="Instances",
    keyword="target_instances",
    prompt="Pick an entity",
    entitiesToPick="ODB_ALL|INSTANCES",
    numberToPick="MANY",
)
RsgTextField(
    p="DialogBox",
    fieldType="Float",
    ncols=12,
    labelText="min radius",
    keyword="rMin",
    default="",
)
RsgTextField(
    p="DialogBox",
    fieldType="Float",
    ncols=12,
    labelText="max radius",
    keyword="rMax",
    default="",
)
RsgCheckButton(p="DialogBox", text="tartget circular edges ? (stable)", keyword="target_circular", default=True)
RsgCheckButton(p="DialogBox", text="target oval edges ? (experimental feature)", keyword="target_ovals", default=False)
RsgCheckButton(p="DialogBox", text="coupling", keyword="coupling", default=True)
dialogBox.show()
